language: objective-c
osx_image: xcode9.2
script: 
- xcodebuild clean test -project TravisIntegration.xcodeproj -scheme TravisIntegration -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3.1" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet

